language: csharp
notifications:
  slack: unolabs:cbusXPH6pBwZ35rVDzi4k4ve
mono: none
dotnet: 2.0.0
dist: trusty
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "UwrzTXEFJWS5UyNGPd0Lui/wcMBaUmQqakQxP6Du6nhZdA7f05CEFY4bRZc/x1QLIZNjGP93rh8Jd1Ubwh5YhgIJ9pkcMfFfHblQ8HzUROKTLsFbwDfanh1mIR4u45fYOh1pGgFMnndU9bBoy8GAxE5V8ca7NwrPiTAMgaP/+8CLLV9UAza/RPOCCa8VzAeljSws7v5NLqBUqbPCr+p8xTSo1QzT0uaLnTbt8V1dLOvr1F8SDXYkKzIYdoKrmWvrWZJqY8kCTt8DYujPgjfw12qBg7/jPAYUnqvqBmJYyehvKugG+nSb5nTQdG4EgouHpC5xdeMuMbO3uRMX7VM1OotI0QsUKjW/SjoYq1dlAtl9DYaSgHtcUOaFdSk2fBNusZ+7DKPsKMb4gxLuJlpUS8j5Snhc35YTIwWVcqsWK/VMtU6v9AbPUUV5p0IrRgtCjBC6xUnGMBusUogWwen8pTBiD/W5VrQNjMs7JIAnh01M15DrwE1gb8GGAwnLkVVpOZHiCl6ZIhB0wRvO40Y9c4rFAqi2SWueqpA0rYU7cwKHAvo8l92kBsRwCS+TendZYt178P2WivYdfplKX0QH2rE90N8V8UCTpcwdsb+SrI0qQFoUqLCv8d3AthxzN2fX3eEXnvqwbsPxb/q4N8a8XxI6DjtEO1qFITLwvgM9dy4="

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
  - dotnet restore
  
addons:
  coverity_scan:
    project:
      name: "unosquare/passcore"
      description: "A self-service password management tool for Active Directory "
    notification_email: geovanni.perez@gmail.com
    build_command_prepend: "dotnet restore"
    build_command: "dotnet build"
    branch_pattern: master
