name: ASP.NET Core CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - uses: actions/cache@v1
      with:
        path: ~/.npm
        key: node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          node-
    - name: npm build
      run: |
        npm ci
        npm run lint
      working-directory: src/Unosquare.PassCore.Web/ClientApp
    - name: Build with dotnet Windows Provider
      run: dotnet build --configuration Release
    - name: Build with dotnet Novell Provider
      run: dotnet build --configuration Release /p:PASSCORE_PROVIDER=LDAP
    - name: Test with Selenium
      working-directory: src/Unosquare.PassCore.Web
      continue-on-error: true
      run: |
        dotnet run &
        sleep 20
        jobs
        curl http://localhost:5000
      env:
        ASPNETCORE_ENVIRONMENT: Development
